### ISSUE TITLE
Reproduce results

### ISSUE THREAD

**Issue by trongtuyen99** [lijfrank-open/GA2MIF#2]
Hi @lijfrank-open , could you please share with me the scripts you used to generate the results in your papers? I've been experimenting with different settings, but IEMOCAP results only reach around 68%, much lower than yours. Thank you!

**Comment by lijfrank** [comment]
> Hi @lijfrank-open , could you please share with me the scripts you used to generate the results in your papers? I've been experimenting with different settings, but IEMOCAP results only reach around 68%, much lower than yours. Thank you!

The results in the paper are from running on our machine. You can try to fine tune the hyperparameters. Additionally, you can try running on multiple GPUs. Thank you for your attention.
