### ISSUE TITLE
some problems about MELD

### ISSUE THREAD

**Issue by shuiguolanzi397** [lijfrank-open/GA2MIF#3]
Thank you for shareing your code on public. Can you show your hyperparameters on MELD? I try many times and I get neatly about 60%. I will appreciate if you can show me partly about the hyperparameters!!

**Comment by lijfrank** [comment]
These results were only what I got on my server. You could try different hyperparameters and multi-GPU runs.

**Comment by shuiguolanzi397** [comment]
Thank you for your reply, and I will try!!!
















At 2024-12-07 17:45:04, "Frank Lee" ***@***.***> wrote:

These results were only what I got on my server. You could try different hyperparameters and multi-GPU runs.
